package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

const header = "// Code generated by cmd/gen from the LangSmith Operation Catalog. DO NOT EDIT.\n\n"

// Flags the generator must not emit because the root or runtime owns them.
var reservedFlags = map[string]bool{
	"format": true, "jq": true, "yes": true, "help": true, "profile": true,
	"workspace": true, "workspace-id": true, "api-url": true, "api-key": true,
}

type flagKind int

const (
	kindString flagKind = iota
	kindInt
	kindFloat
	kindBool
	kindTime
	kindEnum
	kindStringSlice
	kindIntSlice
	kindJSON
)

type flagPlan struct {
	Flag     string
	Wire     string
	Var      string
	Location string // path, query, body
	Kind     flagKind
	Required bool
	Help     string
	GoField  string
	EnumType string
	Enum     []string
	IsCursor bool
	IsLimit  bool
	IsOffset bool
	// IsProject marks session_id, exposed as --project / --project-id.
	IsProject bool
}

// projectParam is the internal name for a project; the CLI says project.
const projectParam = "session_id"

type opPlan struct {
	Op       Operation
	Func     string
	Path     []string
	Flags    []flagPlan
	Columns  []string
	Paginate *Pagination
}

// Options controls generation.
type Options struct {
	// SkipUnsupported drops operations the generator cannot map instead of
	// failing, returning them as warnings. Used to survey catalog coverage.
	SkipUnsupported bool
}

// Generate returns generated Go files keyed by file name.
func Generate(c *Catalog) (map[string][]byte, error) {
	files, _, err := GenerateWith(c, Options{})
	return files, err
}

// GenerateWith is Generate with options; it also returns skipped operations.
func GenerateWith(c *Catalog, opts Options) (map[string][]byte, []string, error) {
	byGroup := map[string][]opPlan{}
	var errs []string
	for _, op := range c.Exposed() {
		plan, err := planOperation(c, op)
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s: %v", op.ID, err))
			continue
		}
		byGroup[op.Resource[0]] = append(byGroup[op.Resource[0]], plan)
	}
	if len(errs) > 0 && !opts.SkipUnsupported {
		return nil, nil, fmt.Errorf("cannot generate:\n  %s", strings.Join(errs, "\n  "))
	}

	files := map[string][]byte{}
	for group, plans := range byGroup {
		src, err := renderFile(plans)
		if err != nil {
			return nil, nil, fmt.Errorf("%s: %w", group, err)
		}
		files["zz_generated_"+group+".go"] = src
	}
	return files, errs, nil
}

func planOperation(c *Catalog, op Operation) (opPlan, error) {
	sdk := op.SDK.Go
	if sdk == nil {
		return opPlan{}, fmt.Errorf("no Go SDK method")
	}
	plan := opPlan{Op: op, Func: "new" + pascal(strings.Join(append(append([]string{}, op.Resource...), op.Action), "_")), Paginate: op.Pagination}
	for _, r := range op.Resource {
		plan.Path = append(plan.Path, kebab(singular(r)))
	}
	plan.Path = append(plan.Path, verb(op.Action))

	seen := map[string]bool{}
	add := func(f flagPlan) error {
		if reservedFlags[f.Flag] {
			return fmt.Errorf("parameter %q collides with the global --%s flag", f.Wire, f.Flag)
		}
		names := []string{f.Flag}
		if f.IsProject {
			names = append(names, "project")
		}
		for _, name := range names {
			if seen[name] {
				return fmt.Errorf("duplicate flag --%s", name)
			}
			seen[name] = true
		}
		plan.Flags = append(plan.Flags, f)
		return nil
	}

	for _, p := range op.Parameters.Path {
		kind := kindString
		switch c.resolve(p.Schema).typeName() {
		case "integer":
			kind = kindInt
		case "number":
			kind = kindFloat
		}
		f := flagPlan{Flag: kebab(p.Name), Wire: p.Name, Var: pascal(p.Name), Location: "path", Kind: kind, Required: true, Help: helpText(p.Description, p.Name)}
		if p.Name == projectParam {
			f.Flag, f.IsProject = "project-id", true
		}
		if err := add(f); err != nil {
			return plan, err
		}
	}

	pg := op.Pagination
	for _, p := range op.Parameters.Query {
		f, err := fieldFlag(c, sdk, p.Name, p.Schema, p.Required, p.Description, "query")
		if err != nil {
			return plan, err
		}
		if pg != nil && pg.ParamLocation == "query" {
			switch p.Name {
			case pg.Request.CursorParam:
				f.Flag, f.IsCursor, f.Kind = "cursor", true, kindString
				f.Help = "Continue from next_cursor of a previous page"
			case pg.Request.OffsetParam:
				f.Flag, f.IsOffset = "cursor", true
				f.Help = "Continue from next_cursor of a previous page"
				f.Kind = kindString
			case pg.Request.LimitParam:
				f.Flag, f.IsLimit, f.Kind = "limit", true, kindInt
				f.Help = "Maximum items to return in this page"
				if pg.Request.LimitMax != nil {
					f.Help += fmt.Sprintf(" (max %d)", *pg.Request.LimitMax)
				}
			}
		}
		if err := add(f); err != nil {
			return plan, err
		}
	}
	if pg != nil && pg.ParamLocation != "query" {
		return plan, fmt.Errorf("pagination with params in the %s is not supported yet", pg.ParamLocation)
	}

	if op.RequestBody != nil {
		body := c.resolve(op.RequestBody.Schema)
		if body == nil || len(body.Properties) == 0 {
			return plan, fmt.Errorf("request body has no object properties")
		}
		required := map[string]bool{}
		for _, r := range body.Required {
			required[r] = true
		}
		names := make([]string, 0, len(body.Properties))
		for name := range body.Properties {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			prop := body.Properties[name]
			desc := prop.Description
			if r := c.resolve(prop); r != nil && desc == "" {
				desc = r.Description
			}
			f, err := fieldFlag(c, sdk, name, prop, required[name], desc, "body")
			if err != nil {
				return plan, err
			}
			if err := add(f); err != nil {
				return plan, err
			}
		}
	}

	if pg != nil {
		plan.Columns = itemColumns(c, op)
	}
	return plan, nil
}

func fieldFlag(c *Catalog, sdk *GoSDK, name string, schema *Schema, required bool, desc, location string) (flagPlan, error) {
	field, ok := sdk.Fields[name]
	if !ok {
		return flagPlan{}, fmt.Errorf("catalog has no Go field for %q", name)
	}
	f := flagPlan{Flag: kebab(name), Wire: name, Var: field.Name, Location: location, Required: required, GoField: field.Name, EnumType: field.EnumType}
	s := c.resolve(schema)
	if s == nil {
		s = &Schema{}
	}
	switch s.typeName() {
	case "string":
		switch {
		case len(s.Enum) > 0 && field.EnumType != "":
			f.Kind = kindEnum
			for _, v := range s.Enum {
				f.Enum = append(f.Enum, fmt.Sprint(v))
			}
		case s.Format == "date-time":
			f.Kind = kindTime
		default:
			f.Kind = kindString
		}
	case "integer":
		f.Kind = kindInt
	case "number":
		f.Kind = kindFloat
	case "boolean":
		f.Kind = kindBool
	case "array":
		item := c.resolve(s.Items)
		switch {
		case item != nil && item.typeName() == "string" && len(item.Enum) == 0:
			f.Kind = kindStringSlice
		case item != nil && item.typeName() == "integer":
			f.Kind = kindIntSlice
		default:
			f.Kind = kindJSON
		}
	default:
		f.Kind = kindJSON
	}
	if name == projectParam && f.Kind == kindString {
		f.Flag, f.IsProject = "project-id", true
		if desc == "" {
			desc = "Tracing project ID"
		}
	}
	if f.Kind == kindJSON {
		if location != "body" {
			return f, fmt.Errorf("%s parameter %q has a structured type; only body fields accept JSON", location, name)
		}
		f.Flag += "-json"
		f.Help = helpText(desc, name) + " (JSON, @file, or @- for stdin)"
	} else {
		f.Help = helpText(desc, name)
	}
	if len(f.Enum) > 0 && !mentionsAll(f.Help, f.Enum) {
		f.Help += " (" + strings.Join(f.Enum, ", ") + ")"
	}
	return f, nil
}

func mentionsAll(text string, values []string) bool {
	for _, v := range values {
		if !strings.Contains(text, v) {
			return false
		}
	}
	return true
}

func itemColumns(c *Catalog, op Operation) []string {
	if op.Response == nil || op.Pagination.Response.ItemsField == nil {
		return nil
	}
	page := c.resolve(op.Response.Schema)
	if page == nil {
		return nil
	}
	arr := c.resolve(page.Properties[*op.Pagination.Response.ItemsField])
	if arr == nil {
		return nil
	}
	item := c.resolve(arr.Items)
	if item == nil {
		return nil
	}
	var cols []string
	if _, ok := item.Properties["id"]; ok {
		cols = append(cols, "id")
	}
	names := make([]string, 0, len(item.Properties))
	for name := range item.Properties {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if name == "id" || len(cols) >= 5 {
			continue
		}
		switch c.resolve(item.Properties[name]).typeName() {
		case "string", "integer", "number", "boolean":
			cols = append(cols, name)
		}
	}
	return cols
}

// --- rendering -------------------------------------------------------------

func renderFile(plans []opPlan) ([]byte, error) {
	sort.Slice(plans, func(i, j int) bool { return plans[i].Op.ID < plans[j].Op.ID })
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("package gen\n\n")
	b.WriteString("import (\n\t\"context\"\n\n\t\"github.com/langchain-ai/langsmith-cli/internal/cmdutil\"\n\t\"github.com/langchain-ai/langsmith-cli/internal/genrt\"\n\t\"github.com/langchain-ai/langsmith-cli/internal/structured\"\n\t\"github.com/langchain-ai/langsmith-go\"\n\t\"github.com/langchain-ai/langsmith-go/option\"\n\t\"github.com/spf13/cobra\"\n)\n\n")

	b.WriteString("func init() {\n")
	for _, group := range groupsFor(plans) {
		fmt.Fprintf(&b, "\tgroups = append(groups, Group{Path: %s, Short: %q})\n", goStrings(group.Path), group.Short)
	}
	for _, p := range plans {
		fmt.Fprintf(&b, "\toperations = append(operations, Operation{ID: %q, Path: %s, Risk: %q, New: %s})\n", p.Op.ID, goStrings(p.Path), p.Op.Risk, p.Func)
	}
	b.WriteString("}\n")

	for _, p := range plans {
		renderOperation(&b, p)
	}
	b.WriteString("\nvar (\n\t_ = langsmith.F[string]\n\t_ = option.WithJSONSet\n\t_ = genrt.Raw\n)\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated code: %w\n%s", err, b.String())
	}
	return src, nil
}

type groupPlan struct {
	Path  []string
	Short string
}

func groupsFor(plans []opPlan) []groupPlan {
	seen := map[string]bool{}
	var out []groupPlan
	for _, p := range plans {
		for i := 1; i < len(p.Path); i++ {
			path := p.Path[:i]
			key := strings.Join(path, " ")
			if seen[key] {
				continue
			}
			seen[key] = true
			var parts []string
			for j, r := range p.Op.Resource[:i] {
				if j < i-1 {
					r = singular(r)
				}
				parts = append(parts, r)
			}
			words := strings.ReplaceAll(strings.Join(parts, " "), "_", " ")
			out = append(out, groupPlan{Path: append([]string{}, path...), Short: "Manage " + words})
		}
	}
	return out
}

func renderOperation(b *bytes.Buffer, p opPlan) {
	op := p.Op
	sdk := op.SDK.Go
	fmt.Fprintf(b, "\n// %s: %s %s\n", op.ID, strings.ToUpper(op.HTTP.Method), op.HTTP.Path)
	fmt.Fprintf(b, "func %s() *cobra.Command {\n", p.Func)

	b.WriteString("\ttype input struct {\n")
	for _, f := range p.Flags {
		fmt.Fprintf(b, "\t\t%s %s\n", f.Var, goType(f.Kind))
		if f.IsProject {
			fmt.Fprintf(b, "\t\t%sName string\n", f.Var)
		}
	}
	b.WriteString("\t}\n")

	fmt.Fprintf(b, "\tcmd := structured.Command[*input]{\n")
	fmt.Fprintf(b, "\t\tUse: %q,\n", p.Path[len(p.Path)-1])
	fmt.Fprintf(b, "\t\tShort: %q,\n", shortText(op))
	fmt.Fprintf(b, "\t\tLong: %q,\n", longText(p))
	b.WriteString("\t\tArgs: cobra.NoArgs,\n")

	b.WriteString("\t\tInput: func(cmd *cobra.Command) *input {\n\t\t\tin := &input{}\n")
	for _, f := range p.Flags {
		help := f.Help
		if f.Required {
			help += " (required)"
		}
		fmt.Fprintf(b, "\t\t\tcmd.Flags().%s(&in.%s, %q, %s, %q)\n", flagFunc(f.Kind), f.Var, f.Flag, zeroValue(f.Kind), help)
		if f.IsProject {
			fmt.Fprintf(b, "\t\t\tcmd.Flags().StringVar(&in.%sName, \"project\", \"\", \"Project name, resolved to --project-id\")\n", f.Var)
			b.WriteString("\t\t\tcmd.MarkFlagsMutuallyExclusive(\"project\", \"project-id\")\n")
		}
	}
	if op.Risk == "DESTRUCTIVE_WRITE" {
		b.WriteString("\t\t\tcmd.Flags().Bool(\"yes\", false, \"Confirm this destructive write\")\n")
	}
	b.WriteString("\t\t\treturn in\n\t\t},\n")

	b.WriteString("\t\tAction: func(ctx context.Context, cmd *cobra.Command, in *input, _ []string) (any, error) {\n")
	var required []string
	for _, f := range p.Flags {
		if f.Required && f.IsProject {
			b.WriteString("\t\t\tif err := genrt.RequiredOneOf(cmd, \"project\", \"project-id\"); err != nil {\n\t\t\t\treturn nil, err\n\t\t\t}\n")
		} else if f.Required {
			required = append(required, strconv.Quote(f.Flag))
		}
	}
	if len(required) > 0 {
		fmt.Fprintf(b, "\t\t\tif err := genrt.Required(cmd, %s); err != nil {\n\t\t\t\treturn nil, err\n\t\t\t}\n", strings.Join(required, ", "))
	}
	for _, f := range p.Flags {
		if f.Kind == kindEnum {
			quoted := make([]string, len(f.Enum))
			for i, v := range f.Enum {
				quoted[i] = strconv.Quote(v)
			}
			fmt.Fprintf(b, "\t\t\tif err := genrt.OneOf(cmd, %q, in.%s, %s); err != nil {\n\t\t\t\treturn nil, err\n\t\t\t}\n", f.Flag, f.Var, strings.Join(quoted, ", "))
		}
	}
	if op.Risk == "DESTRUCTIVE_WRITE" {
		b.WriteString("\t\t\tif err := genrt.ConfirmDestructive(cmd); err != nil {\n\t\t\t\treturn nil, err\n\t\t\t}\n")
	}
	b.WriteString("\t\t\tc, err := cmdutil.GetClient(cmd)\n\t\t\tif err != nil {\n\t\t\t\treturn nil, structured.NewError(structured.CategoryAuthentication, err.Error())\n\t\t\t}\n")
	b.WriteString("\t\t\tvar opts []option.RequestOption\n")
	if sdk.ParamsType != nil {
		fmt.Fprintf(b, "\t\t\tparams := langsmith.%s{}\n", *sdk.ParamsType)
	}
	offsetVar := ""
	for _, f := range p.Flags {
		if f.Location == "path" {
			if f.IsProject {
				fmt.Fprintf(b, "\t\t\tif v, err := genrt.ProjectID(ctx, c, in.%sName, in.%s); err != nil {\n\t\t\t\treturn nil, err\n\t\t\t} else {\n\t\t\t\tin.%s = v\n\t\t\t}\n", f.Var, f.Var, f.Var)
			}
			continue
		}
		renderAssign(b, f)
		if f.IsOffset {
			offsetVar = "offset"
		}
	}

	args := []string{"ctx"}
	for _, name := range sdk.PathArgs {
		args = append(args, "in."+pascal(name))
	}
	if sdk.ParamsType != nil {
		args = append(args, "params")
	}
	args = append(args, "opts...")
	call := fmt.Sprintf("c.SDK.%s.%s(%s)", sdk.Service, sdk.Method, strings.Join(args, ", "))

	// Stainless Go returns only an error when the success response has no body.
	hasResult := op.Response != nil && op.Response.ContentType != nil
	if hasResult {
		fmt.Fprintf(b, "\t\t\tres, err := %s\n", call)
	} else {
		fmt.Fprintf(b, "\t\t\terr = %s\n", call)
	}
	fmt.Fprintf(b, "\t\t\tif err != nil {\n\t\t\t\treturn nil, genrt.APIError(err, %s)\n\t\t\t}\n", flagMap(p.Flags))

	switch {
	case !hasResult:
		b.WriteString("\t\t\treturn map[string]bool{\"ok\": true}, nil\n")
	case p.Paginate != nil:
		b.WriteString(pageExpr(p, offsetVar))
	default:
		b.WriteString("\t\t\treturn genrt.Raw(res), nil\n")
	}
	b.WriteString("\t\t},\n")

	if len(p.Columns) > 0 {
		b.WriteString("\t\tRender: structured.PageTable{Columns: []structured.Column{\n")
		for _, col := range p.Columns {
			fmt.Fprintf(b, "\t\t\t{Header: %q, Template: %q},\n", strings.ReplaceAll(col, "_", " "), fmt.Sprintf("{{field . %q}}", col))
		}
		b.WriteString("\t\t}},\n")
	}
	b.WriteString("\t}.Cobra()\n")
	if op.Deprecated != nil && *op.Deprecated != "" {
		fmt.Fprintf(b, "\tcmd.Deprecated = %q\n", *op.Deprecated)
	}
	b.WriteString("\treturn cmd\n}\n")
}

func renderAssign(b *bytes.Buffer, f flagPlan) {
	if f.IsOffset {
		fmt.Fprintf(b, "\t\t\toffset, err := structured.ParseOffsetCursor(in.%s)\n\t\t\tif err != nil {\n\t\t\t\treturn nil, err\n\t\t\t}\n\t\t\tparams.%s = langsmith.F(offset)\n", f.Var, f.GoField)
		return
	}
	if f.IsProject {
		fmt.Fprintf(b, "\t\t\tif cmd.Flags().Changed(\"project\") || cmd.Flags().Changed(\"project-id\") {\n\t\t\t\tv, err := genrt.ProjectID(ctx, c, in.%sName, in.%s)\n\t\t\t\tif err != nil {\n\t\t\t\t\treturn nil, err\n\t\t\t\t}\n\t\t\t\tparams.%s = langsmith.F(v)\n\t\t\t}\n", f.Var, f.Var, f.GoField)
		return
	}
	fmt.Fprintf(b, "\t\t\tif cmd.Flags().Changed(%q) {\n", f.Flag)
	switch f.Kind {
	case kindEnum:
		fmt.Fprintf(b, "\t\t\t\tparams.%s = langsmith.F(langsmith.%s(in.%s))\n", f.GoField, f.EnumType, f.Var)
	case kindTime:
		fmt.Fprintf(b, "\t\t\t\tv, err := genrt.Time(%q, in.%s)\n\t\t\t\tif err != nil {\n\t\t\t\t\treturn nil, err\n\t\t\t\t}\n\t\t\t\tparams.%s = langsmith.F(v)\n", f.Flag, f.Var, f.GoField)
	case kindJSON:
		fmt.Fprintf(b, "\t\t\t\tv, err := genrt.JSON(%q, in.%s)\n\t\t\t\tif err != nil {\n\t\t\t\t\treturn nil, err\n\t\t\t\t}\n\t\t\t\topts = append(opts, option.WithJSONSet(%q, v))\n", f.Flag, f.Var, f.Wire)
	default:
		fmt.Fprintf(b, "\t\t\t\tparams.%s = langsmith.F(in.%s)\n", f.GoField, f.Var)
	}
	b.WriteString("\t\t\t}\n")
}

func pageExpr(p opPlan, offsetVar string) string {
	pg := p.Paginate
	items := "res.Items"
	if f := pg.Response.ItemsField; f != nil {
		items = "res." + pascal(*f)
	}
	if pg.Type == "cursor" {
		next := "res." + goPath(pg.Response.NextCursorField)
		return fmt.Sprintf("\t\t\treturn structured.NewCursorPage(genrt.RawItems(%s), %s), nil\n", items, next)
	}
	limit := "in.Limit"
	var def int64
	if pg.Request.LimitDefault != nil {
		def = *pg.Request.LimitDefault
	}
	total := "nil"
	var pre string
	if pg.Response.TotalField != "" {
		pre = fmt.Sprintf("\t\t\ttotal := res.%s\n", pascal(pg.Response.TotalField))
		total = "&total"
	}
	if offsetVar == "" {
		offsetVar = "0"
	}
	return fmt.Sprintf("%s\t\t\tlimit := int64(%d)\n\t\t\tif cmd.Flags().Changed(\"limit\") {\n\t\t\t\tlimit = %s\n\t\t\t}\n\t\t\treturn structured.NewOffsetPage(genrt.RawItems(%s), %s, limit, %s), nil\n", pre, def, limit, items, offsetVar, total)
}

func shortText(op Operation) string {
	if op.Summary != "" {
		return op.Summary
	}
	return strings.ReplaceAll(op.Action, "_", " ")
}

func longText(p opPlan) string {
	op := p.Op
	var b strings.Builder
	if op.Description != "" {
		b.WriteString(flagNames(op.Description, p.Flags))
		b.WriteString("\n\n")
	}
	fmt.Fprintf(&b, "API:        %s %s\nRisk:       %s\nOperation:  %s\n", strings.ToUpper(op.HTTP.Method), op.HTTP.Path, op.Risk, op.ID)
	if p.Paginate != nil {
		b.WriteString("\nReturns one page: {items, next_cursor, has_more}. Pass next_cursor to --cursor for the next page.\n")
	}
	example := "langsmith " + strings.Join(p.Path, " ")
	for _, f := range p.Flags {
		if !f.Required {
			continue
		}
		value := "<" + f.Flag + ">"
		if len(f.Enum) > 0 {
			value = f.Enum[0]
		}
		example += " --" + f.Flag + " " + value
	}
	if op.Risk == "DESTRUCTIVE_WRITE" {
		example += " --yes"
	}
	fmt.Fprintf(&b, "\nExamples:\n  %s\n  %s --format json --jq '.'", example, example)
	return b.String()
}

// flagMap is the wire-name -> flag literal passed to genrt.APIError.
func flagMap(flags []flagPlan) string {
	var pairs []string
	for _, f := range flags {
		flag := "--" + f.Flag
		if f.IsProject {
			flag = "--project"
		}
		pairs = append(pairs, fmt.Sprintf("%q: %q", f.Wire, flag))
	}
	sort.Strings(pairs)
	return "map[string]string{" + strings.Join(pairs, ", ") + "}"
}

// flagNames rewrites backticked wire names (`session_id`) to the CLI flags
// that set them, so help text matches what a caller types.
func flagNames(text string, flags []flagPlan) string {
	for _, f := range flags {
		flag := "--" + f.Flag
		if f.IsProject {
			flag = "--project"
		}
		text = strings.ReplaceAll(text, "`"+f.Wire+"`", flag)
	}
	return text
}

func helpText(desc, name string) string {
	// pflag reads a backticked word in usage as the flag's value name.
	desc = strings.ReplaceAll(desc, "`", "")
	desc = strings.TrimSpace(strings.SplitN(desc, "\n", 2)[0])
	if desc == "" {
		return strings.ReplaceAll(name, "_", " ")
	}
	return strings.TrimSuffix(desc, ".")
}

func goType(k flagKind) string {
	switch k {
	case kindInt:
		return "int64"
	case kindFloat:
		return "float64"
	case kindBool:
		return "bool"
	case kindStringSlice:
		return "[]string"
	case kindIntSlice:
		return "[]int64"
	default:
		return "string"
	}
}

func flagFunc(k flagKind) string {
	switch k {
	case kindInt:
		return "Int64Var"
	case kindFloat:
		return "Float64Var"
	case kindBool:
		return "BoolVar"
	case kindStringSlice:
		return "StringSliceVar"
	case kindIntSlice:
		return "Int64SliceVar"
	default:
		return "StringVar"
	}
}

func zeroValue(k flagKind) string {
	switch k {
	case kindInt, kindFloat:
		return "0"
	case kindBool:
		return "false"
	case kindStringSlice, kindIntSlice:
		return "nil"
	default:
		return `""`
	}
}

func goStrings(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = strconv.Quote(s)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func goPath(field string) string {
	parts := strings.Split(field, ".")
	for i, p := range parts {
		parts[i] = pascal(p)
	}
	return strings.Join(parts, ".")
}
