package cmd

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/langchain-ai/langsmith-cli/internal/client"
	"github.com/langchain-ai/langsmith-cli/internal/output"
	"github.com/spf13/cobra"
)

// AlertRule and AlertAction mirror the wire format documented in
// smith-go/alerts/types.go. The langsmith-go SDK is auto-generated by
// Stainless and does not yet have a generated AlertService, so we hit the
// `/alerts/...` endpoints via the CLI client's raw HTTP helpers. When the
// generated service lands, swap c.RawGet/Post/Patch/Delete for c.SDK.Alerts.
type AlertRule struct {
	ID                     string   `json:"id,omitempty"`
	Name                   string   `json:"name"`
	Description            string   `json:"description"`
	Type                   string   `json:"type"`
	Attribute              string   `json:"attribute"`
	Aggregation            string   `json:"aggregation"`
	WindowMinutes          int      `json:"window_minutes"`
	Operator               string   `json:"operator"`
	Threshold              *float64 `json:"threshold,omitempty"`
	ThresholdWindowMinutes *int     `json:"threshold_window_minutes,omitempty"`
	ThresholdMultiplier    *float64 `json:"threshold_multiplier,omitempty"`
	Filter                 *string  `json:"filter,omitempty"`
	DenominatorFilter      *string  `json:"denominator_filter,omitempty"`
	SessionID              string   `json:"session_id,omitempty"`
	SessionName            string   `json:"session_name,omitempty"`
}

// AlertAction matches smith-go's wire format: `config` is a JSON-encoded
// string (not a nested object) because each target type has its own
// schema and the backend stores the raw string.
type AlertAction struct {
	ID          string `json:"id,omitempty"`
	AlertRuleID string `json:"alert_rule_id,omitempty"`
	Target      string `json:"target"`
	Config      string `json:"config"`
}

// AlertResponse is what the API returns from create/get/list/update.
type AlertResponse struct {
	Rule    AlertRule     `json:"rule"`
	Actions []AlertAction `json:"actions"`
}

// AlertCreateRequest / AlertUpdateRequest share the same body shape.
type AlertWriteRequest struct {
	Rule    AlertRule     `json:"rule"`
	Actions []AlertAction `json:"actions"`
}

func newAlertCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "alert",
		Short: "Manage alert rules on tracing projects",
		Long: `Manage alert rules on tracing projects.

Alerts are server-side monitors that fire actions (webhook, PagerDuty,
Dynatrace) when a project's traces meet a threshold or change condition
over a sliding window. Each alert is scoped to one project (session).

For create/update workflows, prefer declarative YAML via:
    langsmith apply -f path/to/alerts/

Examples:
  langsmith alert list --project my-project
  langsmith alert get my-alert --project my-project
  langsmith alert delete my-alert --project my-project --yes`,
	}

	cmd.AddCommand(newAlertListCmd())
	cmd.AddCommand(newAlertGetCmd())
	cmd.AddCommand(newAlertDeleteCmd())
	return cmd
}

func newAlertListCmd() *cobra.Command {
	var (
		project    string
		sessionID  string
		outputFile string
	)

	cmd := &cobra.Command{
		Use:   "list",
		Short: "List alert rules on a project",
		Long: `List alert rules. Requires --project NAME or --session-id ID.

Examples:
  langsmith alert list --project my-project
  langsmith alert list --session-id 01H...`,
		Run: func(cmd *cobra.Command, args []string) {
			ctx := context.Background()
			c := MustGetClient()

			resolved, err := resolveSessionFromFlags(ctx, c, project, sessionID)
			if err != nil {
				ExitErrorf("%v", err)
			}
			alerts, err := alertList(ctx, c, resolved)
			if err != nil {
				ExitErrorf("listing alerts: %v", err)
			}

			fmt_ := GetFormat()
			if fmt_ == "pretty" {
				columns := []string{"Name", "Type", "Attribute", "Window", "Threshold", "Actions"}
				var rows [][]string
				for _, a := range alerts {
					rows = append(rows, []string{
						a.Rule.Name,
						a.Rule.Type,
						a.Rule.Attribute,
						fmt.Sprintf("%dm", a.Rule.WindowMinutes),
						formatThreshold(a.Rule),
						strings.Join(actionTargets(a.Actions), ","),
					})
				}
				output.OutputTable(columns, rows, "Alert Rules")
			} else {
				output.OutputJSON(alerts, outputFile)
			}
		},
	}
	cmd.Flags().StringVar(&project, "project", "", "Project (session) name")
	cmd.Flags().StringVar(&sessionID, "session-id", "", "Session UUID (alternative to --project)")
	cmd.Flags().StringVarP(&outputFile, "output", "o", "", "Write JSON output to a file")
	return cmd
}

func newAlertGetCmd() *cobra.Command {
	var (
		project    string
		sessionID  string
		outputFile string
	)

	cmd := &cobra.Command{
		Use:   "get NAME_OR_ID",
		Short: "Get one alert rule by name or ID",
		Args:  cobra.ExactArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			ctx := context.Background()
			c := MustGetClient()

			resolved, err := resolveSessionFromFlags(ctx, c, project, sessionID)
			if err != nil {
				ExitErrorf("%v", err)
			}
			alert, err := alertGetByNameOrID(ctx, c, resolved, args[0])
			if err != nil {
				ExitErrorf("%v", err)
			}
			output.OutputJSON(alert, outputFile)
		},
	}
	cmd.Flags().StringVar(&project, "project", "", "Project (session) name")
	cmd.Flags().StringVar(&sessionID, "session-id", "", "Session UUID (alternative to --project)")
	cmd.Flags().StringVarP(&outputFile, "output", "o", "", "Write JSON output to a file")
	return cmd
}

func newAlertDeleteCmd() *cobra.Command {
	var (
		project   string
		sessionID string
		yes       bool
	)

	cmd := &cobra.Command{
		Use:   "delete NAME_OR_ID",
		Short: "Delete one alert rule by name or ID",
		Args:  cobra.ExactArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			ctx := context.Background()
			c := MustGetClient()

			resolved, err := resolveSessionFromFlags(ctx, c, project, sessionID)
			if err != nil {
				ExitErrorf("%v", err)
			}
			alert, err := alertGetByNameOrID(ctx, c, resolved, args[0])
			if err != nil {
				ExitErrorf("%v", err)
			}
			if !yes {
				fmt.Printf("Delete alert %q (%s)? [y/N] ", alert.Rule.Name, alert.Rule.ID)
				var resp string
				fmt.Scanln(&resp)
				if !strings.EqualFold(resp, "y") && !strings.EqualFold(resp, "yes") {
					fmt.Println("aborted")
					return
				}
			}
			if err := alertDelete(ctx, c, resolved, alert.Rule.ID); err != nil {
				ExitErrorf("deleting alert: %v", err)
			}
			fmt.Printf("Deleted alert %q\n", alert.Rule.Name)
		},
	}
	cmd.Flags().StringVar(&project, "project", "", "Project (session) name")
	cmd.Flags().StringVar(&sessionID, "session-id", "", "Session UUID (alternative to --project)")
	cmd.Flags().BoolVarP(&yes, "yes", "y", false, "Skip confirmation prompt")
	return cmd
}

// --- HTTP-layer helpers (also reused by `apply`). ---

func alertList(ctx context.Context, c *client.Client, sessionID string) ([]AlertResponse, error) {
	var out []AlertResponse
	// The list endpoint is sometimes wrapped as {"alerts": [...]} and sometimes
	// returns a bare list. Try the bare-list shape first; fall back if needed.
	if err := c.RawGet(ctx, fmt.Sprintf("/alerts/%s", sessionID), &out); err == nil {
		return out, nil
	}
	var wrapped struct {
		Alerts []AlertResponse `json:"alerts"`
	}
	if err := c.RawGet(ctx, fmt.Sprintf("/alerts/%s", sessionID), &wrapped); err != nil {
		return nil, err
	}
	return wrapped.Alerts, nil
}

func alertGetByNameOrID(ctx context.Context, c *client.Client, sessionID, nameOrID string) (*AlertResponse, error) {
	// IDs in LangSmith are UUIDs — fast path: try the by-ID endpoint first.
	// If that 404s, fall back to listing and matching by name.
	var direct AlertResponse
	if err := c.RawGet(ctx, fmt.Sprintf("/alerts/%s/%s", sessionID, nameOrID), &direct); err == nil {
		return &direct, nil
	}
	alerts, err := alertList(ctx, c, sessionID)
	if err != nil {
		return nil, err
	}
	for i := range alerts {
		if alerts[i].Rule.Name == nameOrID || alerts[i].Rule.ID == nameOrID {
			return &alerts[i], nil
		}
	}
	return nil, fmt.Errorf("no alert with name or id %q on this project", nameOrID)
}

func alertCreate(ctx context.Context, c *client.Client, sessionID string, req AlertWriteRequest) (*AlertResponse, error) {
	var out AlertResponse
	if err := c.RawPost(ctx, fmt.Sprintf("/alerts/%s", sessionID), req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func alertUpdate(ctx context.Context, c *client.Client, sessionID, alertID string, req AlertWriteRequest) (*AlertResponse, error) {
	// smith-go validates that body.rule.id matches the path param.
	req.Rule.ID = alertID
	var out AlertResponse
	if err := c.RawPatch(ctx, fmt.Sprintf("/alerts/%s/%s", sessionID, alertID), req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func alertDelete(ctx context.Context, c *client.Client, sessionID, alertID string) error {
	return c.RawDelete(ctx, fmt.Sprintf("/alerts/%s/%s", sessionID, alertID), nil)
}

// --- Small formatting helpers. ---

func resolveSessionFromFlags(ctx context.Context, c *client.Client, project, sessionID string) (string, error) {
	switch {
	case sessionID != "" && project != "":
		return "", fmt.Errorf("specify --project OR --session-id, not both")
	case sessionID != "":
		return sessionID, nil
	case project != "":
		id, err := c.ResolveSessionID(ctx, project)
		if err != nil {
			return "", err
		}
		return id, nil
	default:
		return "", fmt.Errorf("--project or --session-id is required")
	}
}

func formatThreshold(r AlertRule) string {
	switch r.Type {
	case "threshold":
		if r.Threshold != nil {
			return fmt.Sprintf("%s %g", r.Operator, *r.Threshold)
		}
		return r.Operator
	case "change":
		mult := 0.0
		if r.ThresholdMultiplier != nil {
			mult = *r.ThresholdMultiplier
		}
		win := 0
		if r.ThresholdWindowMinutes != nil {
			win = *r.ThresholdWindowMinutes
		}
		return fmt.Sprintf("%s %gx vs %dm baseline", r.Operator, mult, win)
	default:
		return r.Type
	}
}

func actionTargets(actions []AlertAction) []string {
	out := make([]string, 0, len(actions))
	for _, a := range actions {
		out = append(out, a.Target)
	}
	return out
}

// parseActionConfig parses the wire-format `config` JSON string into a generic
// map for comparison/printing. Tolerates non-JSON for forward compat.
func parseActionConfig(raw string) map[string]any {
	out := map[string]any{}
	if raw == "" {
		return out
	}
	_ = json.Unmarshal([]byte(raw), &out)
	return out
}
